### ISSUE TITLE
회원가입 페이지 이메일 & 휴대폰 인증 기능 구현

### ISSUE THREAD

**Issue by younho9** [woowa-techcamp-2020/market-11#13]
## 이슈 요약

<img width="350" src="https://user-images.githubusercontent.com/48426991/86587871-7627be00-bfc5-11ea-8930-4885782e35e4.png">

## 체크리스트

- [x] 이메일 뒷자리는 '직접입력' 선택시에만 활성화 및 직접 작성 가능
- [x] 이메일 주소 필드 선택할 수 있음
    - `이메일 선택`, `직접 입력`, `naver.com`, `hanmail.net`, `nate.com`, `hotmail.com`, `gmail.com`
- [x] 휴대폰 인증 받기 기능시 인증번호를 확인해주세요 메시지 출력

<img width="425" alt="스크린샷 2020-07-06 오후 8 31 39" src="https://user-images.githubusercontent.com/48426991/86588977-b38d4b00-bfc7-11ea-8e50-5c50b216e580.png">

- [x] 인증번호 랜덤 생성하여 alert 창으로 띄우기
- [x] 인증번호 6자리 입력 가능한 input 필드 추가
- [x] '인증받기' 버튼 클릭 후 '2분' 카운트다운 화면 노출
- [x] input 필드에 입력한 인증번호와 alert 창에 표시된 인증번호 같은지 확인하는 로직 추가

**Comment by LimHaksu** [comment]
휴대폰 인증과정 모의로 진행하는 로직을 추가할 필요가 있어보이는데요 alert로 인증번호 보여주는 것이 좋을까요?

**Comment by younho9** [comment]
좋은 방법인거 같습니다!
