### ISSUE TITLE
회원가입 기능 구현

### ISSUE THREAD

**Issue by LimHaksu** [woowa-techcamp-2020/market-11#16]
## 이슈 요약
회원가입 했을 때 백엔드에서 회원가입 로직을 처리하는 기능 구현

## 체크리스트

- [x] Node.js + Express 사용
- [x] (선택) 안전한 패스워드 저장 기법 구현
- [x] 설치 가능한 Embedded DB를 사용한다.
- [x] (선택) 아이디 중복체크 기능 (backend)

## 참고자료

🔗 [생활코딩 express 강의](https://opentutorials.org/course/3370/21378)

**Comment by younho9** [comment]
설치해주신 환경에서 안전한 패스워드 저장 기법, 아이디 중복체크 기능 구현은 제가 해보겠습니다.
