### ISSUE TITLE
가입완료 페이지 마크업

### ISSUE THREAD

**Issue by younho9** [woowa-techcamp-2020/market-11#8]
## 이슈 요약

<img width="350" src="https://user-images.githubusercontent.com/48426991/86583477-4fb25480-bfbe-11ea-85c3-89defacb88bc.png">

- 회원가입 성공시 나타나는 페이지
- 개인정보 화면에 노출

## 체크리스트

- [ ] 용도에 맞는 tag 사용
- [ ] 배치 시에 flex 속성을 사용
- [ ] 메인으로 돌아가는 링크 작동 확인

**Comment by LimHaksu** [comment]
빠르게 작업하셨네요!! 수고하셨습니다.
